// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcZA0xKqvkMvif6rxL7vzk5Wifyulu1H0',
    appId: '1:249334367768:web:b453d3f649685f8fdf256d',
    messagingSenderId: '249334367768',
    projectId: 'authlogin-ce216',
    authDomain: 'authlogin-ce216.firebaseapp.com',
    storageBucket: 'authlogin-ce216.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7WK5xpQdunbxGJmD7nZgwlXY9adOyrbI',
    appId: '1:249334367768:android:e3bf590df6361dfcdf256d',
    messagingSenderId: '249334367768',
    projectId: 'authlogin-ce216',
    storageBucket: 'authlogin-ce216.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFwxv0YtDTWICFyTdMLinLX1H1RTDBETo',
    appId: '1:249334367768:ios:60c22e6dbb7a8bd5df256d',
    messagingSenderId: '249334367768',
    projectId: 'authlogin-ce216',
    storageBucket: 'authlogin-ce216.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFwxv0YtDTWICFyTdMLinLX1H1RTDBETo',
    appId: '1:249334367768:ios:647c98b456554695df256d',
    messagingSenderId: '249334367768',
    projectId: 'authlogin-ce216',
    storageBucket: 'authlogin-ce216.appspot.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
